### PR TITLE
Add ERD document pdf

### PR DESCRIPTION
**Pull request by ClaytonSiby**
The following procedures were implemented in the Social Media Website Milestone 1:

- Created ERD to represent relational connections among entities.
- Friendship and friendship requests to tell if it is a request or confirmed friendship.
- Implemented the file with the ERD in the docs directory in the application's root.
- Downloaded the ERD pdf image from the Lucichart online sketch tool.

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Hello, good job guys :clap: :clap: :clap: :clap:, but you still have some minor changes to do.

- [x] friendship table should have two relationships with the user table.

- [x] you are missing status column in friendship table.

- [x] remove the link between like and post tables and put it between like and comment table.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Hi, it's me again, you forgot to make a small change to the ERD.

- [x] Add another relationship between, user and friendship table.

## Happy Coding :tophat:

**Comment by ClaytonSiby** [comment]
Hi @elmejdki, We managed to make the changes as you required. Thanks for the feedback.

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Hi team! Well done implementing the suggested changes from the earlier review. Keep up the good work.
__[Optional]__ It appears that the first reviewer made a mistake and misguided you when it came to the relationship between the `comment` and `like` tables. This relationship should be between the `like` and `post` table like you had it before. Please make this adjustment before merging your PR. We apologize for this :pray: 

_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by ClaytonSiby** [comment]
Thank you @trekab, we've made the adjustments ( implementing the relationship between post & like ).

**Pull request merged**
